"""next step

Revision ID: 7ea148447c54
Revises: f7caabb7e567
Create Date: 2020-08-11 09:30:16.694487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea148447c54'
down_revision = 'f7caabb7e567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
