"""next step

Revision ID: f7caabb7e567
Revises: 89b4e991f80d
Create Date: 2020-08-11 09:10:01.289860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7caabb7e567'
down_revision = '89b4e991f80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_item',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('listing_id', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_item_listing_id'), 'listing_item', ['listing_id'], unique=False)
    op.create_table('order_detail',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('order_id', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_listing_item_listing_id'), table_name='listing_item')
    op.drop_table('listing_item')
    # ### end Alembic commands ###
